### ISSUE TITLE
Datensatz

### ISSUE THREAD

**Issue by rgb19** [rgb19/Gruppe5_WissArbeiten_WiSe_2324#6]
Es ist zwar dafür nichts vorgegeben, aber wäre es für "Deck" nicht besser, dass als Faktor einzuspeichern?
Ist ja einfach dichotom.

**Comment by Garyzan** [comment]
Das Merkmal Deck ist nicht dichotom.
Wenn es um das Merkmal Side geht, kann man drüber nachdenken
